### ISSUE TITLE
Consider removing lodash dependency

### ISSUE THREAD

**Issue by tuler** [codeandcats/classy-commander#343]
One of the nice things about `commander` is how lightweight it is, with only around 176kb.

By depending on `lodash` we add 1.35mb to the package.

Bundling and tree-shaking can help with that, but I don't see a real reason to use lodash here.
There are only 2 calls to `lodash`, one at `modules.getUniqueModuleNames` and another at `commander. getCommandDefinitionUsage`.

Those can easily be replaced with simple typescript code.

If that change is ok I can open a PR.

**Comment by codeandcats** [comment]
Hi @tuler,

Thanks for the heads-up.

I just had a quick look at the code and noticed it's importing the entire root level lodash module. I think lodash has individual files for each of their functions so we should be able to import just the specific ones we need. I would try that path first.

I'd welcome a PR, just please keep the test coverage the same. Thanks
